config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'comments/create'

  get 'comments/destroy'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  get 'home/index'

  get 'home/about'

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected
    def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || root_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
   @comment=Comment.new(comment_params)
   @comment.post_id=params[:post_id]
   @comment.save
   
   redirect_to :back
  end

  def destroy
    @comment=Comment.find(params[:id])
    @comment.destroy

    redirect_to :back
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:제목, :내용)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/home/about.html.erb
<div class="about">
<h1>멋사 6기</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam et ligula tempus, feugiat ante vitae, porta leo. Quisque lobortis mi eget tortor sagittis, quis tristique libero laoreet. In quis purus in risus sodales maximus quis eget eros. Vivamus consectetur placerat ante, sit amet malesuada mauris dapibus quis. Morbi sit amet augue congue, luctus metus nec, molestie metus. Aenean sed rutrum sapien, sit amet pellentesque orci. Pellentesque iaculis consectetur est, tincidunt efficitur tellus posuere ac. Praesent elementum erat in malesuada ullamcorper. In fringilla nulla in suscipit porta. In et neque purus.
</p>
</div>

app/views/home/index.html.erb
<div id="carouselExampleSlidesOnly" class="carousel slide bg-secondary" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag("pic1.jpeg", :class => "rounded d-flex", :alt => "First slide",  style: "height: 480px; width: 100%;")%>
    </div>
    <div class="carousel-item">
      <%= image_tag("pic2.jpeg", :class => "rounded d-flex", :alt => "Second slide", style: "height: 480px; width: 100%;")%>
    </div>
    <div class="carousel-item">
      <%= image_tag("pic3.jpeg", :class => "rounded d-flex", :alt => "Third slide", style: "height: 480px; width: 100%;")%>
    </div>
  </div>
</div>
<div class="container-fluid p-3 mb-2 text-white d-flex p-2 bg-secondary" >
    <h1>멋쟁이 사자처럼입니다.</h1>
    <button type="button" class="btn btn-secondary btn-lg">
    <%= link_to '위대한 여정 함께하기' , posts_path, style: 'color:#FFFFFF;'%>
    </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background-color: #6c757d;">
  <head>
    <title>NEXT X 멋쟁이사자처럼</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="nav">
    
    <a class="nav-item nav-link bg-dark text-white" href="/">Home</a>
    <a class="nav-item nav-link bg-dark text-white" href="/home/about">소개</a>
    <a class="nav-item nav-link bg-dark text-white" href="/posts">게시판</a>
    
    <% if user_signed_in? %>
      <li class="nav-item nav-link bg-dark">
      <%= link_to('로그아웃', destroy_user_session_path, method: :delete, class: "text-white") %>        
      </li>
    <% else %>
      <li class="nav-item nav-link bg-dark">
      <%= link_to('로그인', new_user_session_path, class: "text-white" )  %>  
      </li>
      <li class="nav-item nav-link bg-dark">
      <%= link_to('회원가입', new_user_registration_path, class: "text-white")  %>
      </li>
    <% end %>  
    </nav>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <div class="about">
    <%= yield %>
    </div>
  

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  
  </body>

</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :제목 %>
    <%= f.text_field :제목 %>
  </div>

  <div class="field">
    <%= f.label :내용 %>
    <%= f.text_field :내용 %>
  </div>

  <div class="actions">
    <%= f.submit  "글 작성"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="about">
<h1>수정하기</h1>

<%= render 'form', post: @post %>

<%= link_to '뒤로', posts_path, style: 'color:#FFFFFF;' %>
</div>

app/views/posts/index.html.erb
<div class="about">
<p id="notice"><%= notice %></p>

<h1>게시판</h1>

<table>
  <thead>
    <tr>
      <th>제목</th>
      <th>내용</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td width="600px"><%= link_to post.제목, post, style: 'color:#FFFFFF;' %></td>
        <td><button type="button" class="btn btn-secondary btn-lg d-flex align-self-end">
        <%= link_to '수정하기', edit_post_path(post), style: 'color:#FFFFFF;' %>
        </button></td>
        <td><button type="button" class="btn btn-secondary btn-lg d-flex align-self-end">
        <%= link_to '삭제', post, method: :delete, data: { confirm: '확실합니까?' }, style: 'color:#FFFFFF;' %>
        </button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to '새 글 쓰기', new_post_path, style: 'color:#FFFFFF;' %>
</div>

app/views/posts/new.html.erb
<div class="about">
<h1>새 글</h1>

<%= render 'form', post: @post  %>

<%= link_to '뒤로가기', posts_path, style: 'color:#FFFFFF;' %>
</div>

app/views/posts/show.html.erb
<div class="about">
<p id="notice"><%= notice %></p>

<p>
  <strong>제목:</strong>
  <%= @post.제목 %>
</p>

<p>
  <strong>내용:</strong>
  <%= @post.내용 %>
</p>

<%= link_to '수정', edit_post_path(@post), style: 'color:#FFFFFF;' %> |
<%= link_to '뒤로', posts_path, style: 'color:#FFFFFF;'%>

<%=form_for Comment.new, url:post_comments_path(@post.id) do |f|%>
  <%=f.label "댓글"%>
  <%=f.text_field :content%> <br>
  <%=f.submit '작성'%>
<% end%>

<% @post.comments.each do |comment|%>
  <%=comment.content %>
  <%=link_to '[이 댓글 파괴]', post_comment_path(@post.id, comment.id), method: 'delete', style: "color:white" %><br>
<% end%>
</div>